### ISSUE TITLE
Performance regression in dataflow task scripts

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/ProGraML#147]
#142 appears to have caused a large performance regression for the dataflow task GGNN loops.

Performance **now**: ~2 graphs / sec for training/validation, and ~12 graphs / sec for validation
Performance **before**: ? (need to repo)

**Comment by sarathsankar** [comment]
Hi @ChrisCummins,

The number varies, while _training_ earlier it was around __40 graphs/s__. 
For _validation_: __211 graphs/s__
Since there was halting-issue earlier, I don't have a number for _testing_.
Hope, below screenshot may help you.

![programl_reachability_test_halt](https://user-images.githubusercontent.com/14892005/100703033-c403ef00-33c8-11eb-846b-c29b7b958221.PNG)

Regards,
Sarath KS

**Comment by ChrisCummins** [comment]
Excellent, thanks for that @sarathsankar. I'm going to be off-the-grid for a couple of weeks but will take a look as soon as I'm back. This is high priority, release blocking.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Superseded by #178.
