### ISSUE TITLE
[program explorer] Unable to download jQuery

### ISSUE THREAD

**Issue by Jackwin** [ChrisCummins/ProGraML#148]
Hi  folks,

The RroGraML job is wonderful and awesome. If anyone could answer the following questions or give any insight, that would be great.

1.  The program explorer seems not to work on the web Chrome browser with version 86.0.4240.198. There is no display for the ProGraML and Graph.
2. How to run a flow from a simple cpp application to the LLVM IR and to the graph display? I wonder whether it could translate from an LLVM IR to the graph? If possible, what should I do, supposing the LLVM IR already exists.

Thanks

**Comment by ChrisCummins** [comment]
Hi @Jackwin,

Thanks for reaching out.

### 1. Program explorer not working

That's strange. I don't image there would be any problem with the version of Chrome that you are using. Would you mind opening up the Developer console (in the menu, select View >> Developer >> JavasScript Console) and letting me know it is reporting any errors? It would be helpful as well if you could attach a screenshot. For example, here is what it looks like for me:

![image](https://user-images.githubusercontent.com/1636663/100995027-24249d80-354f-11eb-8458-9c2a99ef3624.png)

### 2. How to go from C++ application to a graph display

1. Install the ProGraML command line tools (see [installation](https://github.com/ChrisCummins/ProGraML#installation) for details).
2. Compile your C++ code to LLVM-IR. The way to do this to modify your build system so that clang is passed the `-emit-llvm -S` flags, e.g.
```
$ clang-10 -emit-llvm -S -c my_app.cpp -o my_app.ll
```
If your C++ applications contains multiple files, you can compile each one to LLVM-IR and then link them, for example:
```
$ clang-10 -emit-llvm -S -c foo.cpp -o foo.ll
$ clang-10 -emit-llvm -S -c bar.cpp -o bar.ll
$ llvm-link foo.ll bar.ll -S -o my_app.ll
```
3. Generate a ProGraML graph from the LLVM-IR using the `llvm2graph` commnand:
```
$ llvm2graph < my_app.ll > my_app.pbtxt
```
4. Generate a Graphviz dotfile for the graph:
```
$ graph2dot < my_app.pbtxt > my_app.dot
```
5. You can now render the Graphviz file and view it however you want, for example as a PNG image:
```
$ dot -Tpng my_app.dot -o my_app.png
```

Hope that helps!

Cheers,
Chris

**Comment by Jackwin** [comment]
Hi @ChrisCummins 

Thank you for your response. The flow from one application to the graph display executes successfully. Perfect!

For the web version, there seem to be some errors, shown as follows. 
![ProGraML_error](https://user-images.githubusercontent.com/4569334/101136003-9e384d80-3647-11eb-8cd8-4077b6b6afc3.png)

Thanks

**Comment by ChrisCummins** [comment]
Hi @Jackwin, thank you for the details. From the screenshot you posted I see that your browser is unable to download jquery, which is required to run the demo. I'm not sure of what could be causing this but fill investigate once I'm back from vacation in a couple of weeks.

Cheers,
Chris

**Comment by Jackwin** [comment]
Hi @ChrisCummins,  take your time and enjoy your vacation:)

**Comment by ChrisCummins** [comment]
Hi @Jackwin, unfortunately, I haven't been able to reproduce the issue. I can't find any reports of issues with the CDN that I'm using, https://code.jquery.com/jquery-3.5.1.min.js . I can only assume it's a local network error. I'll leave this open for a while in case anyone else is affected.

You could always try running the [Flask app](https://github.com/ChrisCummins/program_explorer) locally.

Cheers,
Chris

**Comment by Jackwin** [comment]
Hi @ChrisCummins, The command style works for me, so the web version could be ignored for me.  Thanks again.

**Comment by ChrisCummins** [comment]
Okay great :)
