### ISSUE TITLE
Inst2Vec Node Embedding DevMap

### ISSUE THREAD

**Issue by anon767** [ChrisCummins/ProGraML#158]
## ❓ Questions and Help

I tried to embed the IR Statements from the Devmap (amd) dataset using the following command:
`bazel-bin/bin/inst2vec --directory /Users/<User>/Projects/programlmodel/devicemap/graphs_amd`
As taken from the paper ProGraML: For the Case Study "Device Mapping", the pre-trained inst2vec embeddings were used. 

The IR seems to be correctly preprocessed and the embedding index was successfully added to the graphs. However, from 490103 IR Statements, only three distinct indices were generated and attached to the node features: _8564, 8565, 8566_  (!UNK, !IDENTIFIER, !IMMEDIATE).

Am I doing something wrong here or is this a bug?

Thanks in advance and regards

**Comment by ChrisCummins** [comment]
Hi @anon767, thanks for the report. That doesn't seem right, I'm guessing the inst2vec encoder is not looking at the right field when doing the vocab lookups. I'll take a look at this, though now that my day job is working on another [compiler thing](https://github.com/facebookresearch/CompilerGym), it might take me a few days to find the time to dig into it.

I'll get back to you ASAP! :)

Cheers,
Chris

**Comment by anon767** [comment]
Hey Chris,

thank you very much!
I guess the bug would also occur if I try to embed the nodes from another dataset e.g. the Algorithm Classification dataset, wouldn't it?
And CompilerGym looks pretty neat, I'll check it out, maybe this could be a fit to my research :)

**Comment by ChrisCummins** [comment]
Hey @anon767, cool! Feel free to ping me at chrisc.101@gmail.com if you want to set up a quick call, always good to connect with compiler researchers :)

I fixed the bug you are experiencing. Turns out I had completely broke the inst2vec encoder. Thankfully only a [2 line fix](https://github.com/ChrisCummins/ProGraML/pull/160/files). Thanks for reporting!

If you update to the latest development branch you will get the fix:

```
git fetch origin
git pull --rebase
bazel run -c opt //bin:inst2vec -- --directory /Users/<User>/Projects/programlmodel/devicemap/graphs_amd
```

And yes, this bug affected all datasets you ran `inst2vec` on

Cheers,
Chris
