### ISSUE TITLE
Function-Level Graph

### ISSUE THREAD

**Issue by xrkk** [ChrisCummins/ProGraML#161]
## 🚀 Feature

To get function-level XFG, to be used in tasks like binary diffing.

## Motivation

Function-Level binary diffing has many usages scenarios like vulnerability hunting.

## Pitch

Parse entire LLVM-IR files, generate XFG for each function, and use trained model to generate vector for each function XFG, then use something like LSH(Locality Sensitive Hashing) to quickly locate functions similar to (pre-identified) vulnerable ones.

**Comment by ChrisCummins** [comment]
Hi @xrkk,

Each node in a ProGraML graph has a [Node.function](https://github.com/ChrisCummins/ProGraML/blob/development/programl/proto/node.proto#L44) attribute that tracks the function that the node came from. If you wanted to create per-function graphs, you could create `n` copies of each graph (where n is the number of [ProgramGraph.function](https://github.com/ChrisCummins/ProGraML/blob/development/programl/proto/program_graph.proto#L42) list), then filter each so that only the nodes from one function are included.

Would this do what you want?

Cheers,
Chris

**Comment by xrkk** [comment]
Yes, this can meet my needs. Thank you.

**Comment by ChrisCummins** [comment]
Okay great :)
