### ISSUE TITLE
llvm2graph parsing .ll fail: error: invalid field 'variables'

### ISSUE THREAD

**Issue by xrkk** [ChrisCummins/ProGraML#170]
## To Reproduce

(Tested on WSLv1)
1. Download latest release
1. Download Dataset, extract blas-3.8.0.69052.f90.ll
1. Execute `llvm2graph < blas-3.8.0.69052.f90.ll`, log:
```
E 2021-06-16 05:35:14 [bin/llvm2graph.cc:143] 1684:167: error: invalid field 'variables'
    !5 = distinct !DISubprogram(name: "stpmv", scope: !2, file: !3, line: 143, type: !6, isLocal: false, isDefinition: true, scopeLine: 143, isOptimized: false, unit: !2, variables: !4)
                                                                                                                                                                          ^
```

## Environment

- ProGraML version (if building from source, use `git rev-parse HEAD`): pre-built release, latest version
- How you installed ProGraML (source, pip): pre-built release
- OS: WSLv1
- Python version: 3.8.5
- Build command you used (if building from source):
- GCC/clang version (if building from source):
- Bazel version (if building from source):
- Versions of any other relevant libraries:

**Comment by ChrisCummins** [comment]
Hi @xrkk, thanks for the report! Would you mind uploading the `blas-3.8.0.69052.f90.ll` file as an attachment to this issue? (I know it's in the the public dataset but I don't currently have a machine with it unpacked on ;-) )

The dataset was generated with LLVM 6.0.0, ProGraML now uses LLVM 10.0.0. That probably explains the error while parsing the IR as the metadata format can change between versions. Perhaps it only affects the Fortran code.

The fix will be for me to add an `llvm2graph-6` binary to use. I will do that for the next release (in a week or two). In the meantime, if you are blocked on this then you can build llvm2graph from source from an older revision of this repository before we switched to LLVM 10.0.0.

Hope that helps.

Cheers,
Chris

**Comment by xrkk** [comment]
I am using LLVM-8. Adding pre-compiled `llvm2graph-6` is great but can I add custom LLVM version?

**Comment by ChrisCummins** [comment]
So sorry for the slow reply! I actually recently overhauled the ProGraML API so that you can now `pip install programl` to get pre-compiled llvm2graph binaries for all supported versions. See [getting started](https://github.com/ChrisCummins/ProGraML#getting-started) for more details.

Unfortunately adding support for a custom LLVM version is not trivial. The `llvm2graph` binary is tightly coupled with the LLVM APIs, and adding support different versions sometimes requires small modifications to the code, [e.g.](https://github.com/ChrisCummins/ProGraML/blob/development/programl/ir/llvm/internal/program_graph_builder.cc#L437-L457).

If the currently supported list of LLVM versions (3.8, 6, 10) do not work for you then please feel free to file a feature request issue for a different version!

Closing this as using the new [programl.from_llvm_ir()](https://chriscummins.cc/ProGraML/api/python.html#programl.from_llvm_ir) API provides backwards compatibility by specifying the version:

```py
with open("my-ir.ll") as f:
    programl.from_llvm_ir(f.read(), version="6")
```

Cheers,
Chris
