### ISSUE TITLE
Question: application of the ProGraML

### ISSUE THREAD

**Issue by Hanseltu** [ChrisCummins/ProGraML#177]
## ❓ Questions and Help

Hi guys. Thanks for your nice work on making the representation of a program more precise. I hope this is the right place to ask a question.

I am enthusiastic about compiler testing. Although such a new representation is more suitable for ML-based tasks, I still want to seek your suggestion about the feasibility of the application of ProGraML to compiler testing. The idea is that since you have transfer LLVM IR to a more representable format, is it possible for users to modify ProGraML and then revert changed ProGraML to LLVM IR?

The challenges would be how to conduct semantic-preserving mutation on the ProGraML and how to revert ProGraML back to LLVM IR. The first challenge may not be much difficult to solve than the second one I think. How about your ideas? 

Any suggestions are welcome! Thank you very much!

Best regards,
Haoxin

**Comment by ChrisCummins** [comment]
Hi @Hanseltu, 

Thanks for the question and my apologies for the slow reply!

Every node in a ProGraML graph contains the full text of the line of IR that it was derived from, so yes it should be possible to recover the original IR from a ProGraML graph by traversing the control flow graph and emitting the text of each instruction node in-order.

However, making semantics-preserving edits to the graphs may be tricky, though potentially still easier than editing plain text. For example, let's say you wanted to remove an instruction from a program. In ProGraML that would mean removing a node from a graph. By looking at the incoming / outgoing data edges of that node you could check that removing this statement wont change any memory accesses, but after removing the instruction node and "reconnecting" the predecessor and successor instructions, the text string of the LLVM IR that represents each node may no longer be valid. For example, I believe that removing the second line of this IR would be invalid because then there would be a missing `%2` in the resulting IR:

```llvm
%1 = add %foo %bar
%2 = sub %foo %bar
%3 = mul %foo %bar
```

If you could share some more details on the kinds of mutations you have in mind then that may be useful.

Cheers,
Chris

**Comment by Hanseltu** [comment]
Hi @ChrisCummins. Thanks for your insightful comments!

For now, the mutations in my mind are not very mature and I still trying to find the justification here. I agree with you that more fine-grained modification may be hard to guarantee validity after doing the modification, so I was thought about mutating in a more coarse-grained manner. Basically, I want to try first is modification like "dead code" deletion. Such "dead" may not only be some code regions that will not be executed (in call-graph), it also could be some "dead" (say "duplicate" may be better) regions in data/control-graph. 

For example, in the following code, deleting the first four lines in `if.then` block may not change the semantic of this code. As the branch is always false. One extra work to make the code compile is to update the following label numbers. Such a deletion looks reasonable to handle, but as I mentioned, the rationales behind are still not clear for now. That is, what difference/benefits could be compared to source code deletion.

```
define dso_local i32 @foo() #0 {
entry:
  %a = alloca i32, align 4
  %b = alloca i32, align 4
  store i32 0, i32* %a, align 4
  store i32 1, i32* %b, align 4
  %0 = load i32, i32* %a, align 4
  %tobool = icmp ne i32 %0, 0
  br i1 %tobool, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  %1 = load i32, i32* %a, align 4
  %2 = load i32, i32* %b, align 4
  %add = add nsw i32 %1, %2
  store i32 %add, i32* %a, align 4
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  %3 = load i32, i32* %b, align 4
  %4 = load i32, i32* %a, align 4
  %sub = sub nsw i32 %3, %4
  store i32 %sub, i32* %a, align 4
  %5 = load i32, i32* %a, align 4
  ret i32 %5
}
```

I am more concerned about the later part --- modification on data/control-graph. I think it's possible that there is more than one data-flow path from one variable to another variable. That means, deleting one of the paths will not change the semantic of the code (This looks like doing the compiler optimization). The rationale behind this could be we delete some IR code that compilers are going to optimize, and potentially the optimizations may meet some troubles on it. 

Do you think modification with a more coarse-grained manner on a graph and then recovering the modified graph to IR code is possible? Anyway, I am still thinking about the justification here. Please forgive me if this question makes you confused and I apologize for any bothering I bring to you :)

Thank you so much and any suggestions are welcome!


Best,
Haoxin

**Comment by Hanseltu** [comment]
Just close this issue and will let you know if I have any further updates. Thanks!
