### ISSUE TITLE
End-to-End Debug with LLVM, ProGraML & gdb

### ISSUE THREAD

**Issue by KevinCJHuang** [ChrisCummins/ProGraML#195]
## ❓ Questions and Help

When setting up ProGraML with bazel, is there any way to set up an end-to-end debug experience with my own llvm?

## Additional Context
What I've done so far:
1. I've followed this [link](https://bazel.build/basics/getting_started.html#debugging-bazel) to turn on debug mode in the bazel build script.
2. When using gdb, I found that this only enables part of the gdb functionalities. It doesn't print some llvm functions (e.g. `someObject.dump()`) with a symbol not found error message.

Thank you in advance.

**Comment by ChrisCummins** [comment]
Hi @KevinCJHuang, good question! Unfortunately, the way that the ProGraML build is configured means you won't be able to enable a debug build of LLVM. This is because ProGraML compiles and links against a prebuilt LLVM release that it downloads, it does not build LLVM from scratch.


If you are comfortable working with bazel you can take a look at the LLVM dependency [here](https://github.com/ChrisCummins/ProGraML/blob/development/tools/bzl/deps.bzl#L23-L30) and swap it out for a debug build. Another approach, recently adopted by the sister project [CompilerGym](https://github.com/facebookresearch/CompilerGym), is to build LLVM as part of the main build, but this requires a significant reworking of the existing build system (in the case of CompilerGym we rewrote the build system using CMake). Patches welcome!

Cheers,
Chris
