### ISSUE TITLE
Generating ProgramL graphs from partial code

### ISSUE THREAD

**Issue by gystar** [ChrisCummins/ProGraML#204]
Dear authors, I'm deeply interested in this work!
I find that I can generate graphs via your web tool from partial code, which contains some undefined functions.
For example:
`int test(int a){
 int b = sum(a);
}
`
Where "sum" is not acturally defined.
But I found that the code with undefined types can not be successfully compiled.
For example:
`int test(T a){
 T b = sum(a);
}
`
Where "T" is an undefined type.

Is there some way to generate graphps for partial code with some undefined types?
I think this feature should be very helpful for many tasks, and it is very important for general use of ProgramL.

**Comment by ChrisCummins** [comment]
This is an interesting use case, but it might take a bit of work. We use clang to parse the input source code and generate an `llvm::Module`:

https://github.com/ChrisCummins/ProGraML/blob/cd7d2939d485d989a9b105723fed989bcaca1f94/programl/bin/clang2graph.cc#L143-L146

In your above examples, `sum()` works because LLVM can generate a call instruction to this undefined function. `T`, on the other hand, does not work because without a type definition, LLVM doesn't know what IR instructions it can use to assign/manipulate variables of type `T`.

One thing you could consider is providing "dummy" type definitions for undefined types. Another approach would be to generate the ProGraML graph from something like an AST that doesn't require type definitions to be constructed. Both would have a tradeoff.

Cheers,
Chris

**Comment by gystar** [comment]
Thanks very much!
I think generating some ProgramL-like graphs from AST is very interesting.
Currently some program graphs , e.g.,code property graph (CPG), play similar roles. But CPG has too many semantic-agnostic nodes.

Best wishes!

**Comment by ChrisCummins** [comment]
Sounds good. I would be happy to review patches adding an AST frontend :)

Cheers,
Chris

**Comment by gystar** [comment]
I will try it after I have a more clear idea. 

Thanks.
