### ISSUE TITLE
inst2vec preprocessing is garbage-ish

### ISSUE THREAD

**Issue by Zacharias030** [ChrisCummins/ProGraML#59]
It has problems with whitespace, somehow not reducing the consecutive spaces on this node:
```
node_data={'type': 0, 'text': 'switch i32 %18, label %78 [\n    i32 1, label %19\n    i32 2, label %60\n  ], !dbg !498, !prof !499', 'preprocessed_text': 'switch i32 <%ID>, label <%ID> [\n    i32 <INT>, label <%ID>\n    i32 <INT>, label <%ID>\n  ]', 'function': 'check_refine', 'x': [8564], 'y': [], 'llvm_profile_total_weight': 4925879498}
```

anyway I'm marking this as discussion, because clearly inst2vec preprocessing is beyond rescue and we should pick and choose from the good ideas.

**Comment by ChrisCummins** [comment]
Hey @Zacharias030,

I think "garbage-ish" is a little strong :) The way I see it, there's three types of issue:

1. Edge cases or bugs in the original inst2vec implementation.
2. Bugs introduced because of the way we are interacting with inst2vec (e.g. in the case of #57 where I had missed a part of inst2vec's pre-processing pipeline).
3. Weaknesses in the design of inst2vec which our graph representation can overcome (e.g. not requiring a statement node to encode information about operands).

In the example you gave, it probably falls into category (1) or (2). Either way, I have a tracking issue #55 which we can use for logging feature requests / bugs in the current implementation.
