### ISSUE TITLE
32bit overflow on profile info

### ISSUE THREAD

**Issue by Zacharias030** [ChrisCummins/ProGraML#60]
I see suspicious branch counts in the data:

```
4194304 2143289344 2147483648
63 3845 3908
246017 3845 249862
246017 3845 249862
1064949 2146418699 2147483648
3845 238329 242174
```

However, for now this is a) low priority at this point and b) obviously needs triage before further action.

**Comment by Zacharias030** [comment]
https://github.com/ChrisCummins/phd/pull/100
shows that the counts are implemented as uint32 in the protobuf. This is probably biting us again here!
```
ProgramGraph.LlvmProfile.total_count (uint32)
ProgramGraph.LlvmProfile.max_count (uint32)
ProgramGraph.LlvmProfile.max_internal_count (uint32)
```

**Comment by ChrisCummins** [comment]
Since we restructured the ProGraML representation this type of overflow should not be possible in the photos, we use exclusively int64s now:
https://github.com/ChrisCummins/ProGraML/blob/6c4ea50639773009e7c287feb62c6994fa4f3445/programl/ir/llvm/internal/program_graph_builder.cc#L328-L338

But please re-open if you see anything more suspicious!

Cheers,
Chris
